config/routes.rb
Tv::Application.routes.draw do
  resources :sites

  root :to => 'home#index'
end

app/models/concur.rb
class Concur < ActiveRecord::Base
  attr_accessible :site_id, :url

  belongs_to :sites
end

app/models/site.rb
class Site < ActiveRecord::Base
  attr_accessible :url
  has_many :concurs, dependent: :destroy
  validates :url, uniqueness: true


  require 'nokogiri'

  def page

    url = read_attribute(:url)
    result = recursive_iframe(url)
    p result

    result[:maybe].each do |url|
      p Nokogiri.HTML(RestClient.get(url)).css('object')
    end

    result[:maybe]
  end

private

  # gathers all pages nested via iframe
  def recursive_iframe(url, urls=[], hits=[])

    response = RestClient.get(url) do |response, request, result, &block|
      
      case response.code
      when 404, 406, 504
        nil
      else
        response.return!(request, result, &block)
      end

    end

    unless response.nil?
      html = Nokogiri.HTML(response)

      # current html searches
      hit = source_search(url, html)
      hits << hit unless hit.nil?

      #puts form_search(url, html)

      # iframe recursion
      html.css('iframe').each do |iframe| 
        src = iframe.attr('src')

        # check for protocol
        unless src =~ /^https?:\/\//i
          uri = URI.parse(url)
          
          if src =~ /^\//
            # absolute path
            src = "#{uri.scheme}://#{uri.host}#{src}"
          else
            # relative path
            src = "#{url}/#{src}"
          end

        end

        next unless valid_url?(src)
        next if urls.include?(src)

        puts src
        (urls << src).flatten

        recursive_iframe(src, urls, hits) 
      end

    end

    urls.uniq!
    hits.flatten!
    hits.uniq!


    {
      poor: urls,
      maybe: hits
    }

  end

  # raises potential video page by looking for specific scripts
  def source_search(url, html)

    hits = []

    html.css('script,embed,object').each do |source|

      # attributes
      data = source.attr('data')
      src = source.attr('src')

      if src.nil?
        # load script and parse?
      else
        # check src lib name
        hits << url if src =~ /swfobject.js|player.swf/i
        hits << url if data =~ /player.swf/i
      end
    end

    hits.uniq!

  end

  # submits form to discover additional pages
  def form_search(url, html)

    forms = []
    html.css('form').each do |form|

      action = form.attr('action')

      action = url if action.nil?

      # prefix relative base url if no protocol
      unless action =~ /^https?:\/\//i
        uri = URI.parse(action)

        if action =~ /^\//
          # absolute path
          src = "#{uri.scheme}://#{uri.host}#{action}"
        else
          # relative path
          src = "#{url}/#{action}"
        end  

      end


      data = { 
        method: (form.attr('method') || 'post').downcase, 
        action: action,
        params: form.css('*[name]').map do |i| 
          { 
            name: i.attr('name'), 
            value: i.attr('value')
           }
        end
      }

      forms << data

      # case data[:method]
      #   when 'get'
      #     puts RestClient.get(form[:action])
      #   when 'post'
      #     puts RestClient.post(form[:action], form[:params])
      #   when 'put'
      #   else 
      #     # do nothing
      #   end

      # end

    end

    forms

  end

  def valid_url?(url)
    uri = URI.parse(url)
    uri.kind_of?(URI::HTTP)
  rescue URI::InvalidURIError
    false
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index

  end
end

app/controllers/sites_controller.rb
class SitesController < ApplicationController

  def index
    @sites = Site.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @sites }
    end
  end

  def show
    @site = Site.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @site }
    end
  end

  def new
    @site = Site.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @site }
    end
  end

  def edit
    @site = Site.find(params[:id])
  end

  def create
    @site = Site.new(params[:site])

    respond_to do |format|
      if @site.save
        format.html { redirect_to @site, notice: 'Site was successfully created.' }
        format.json { render json: @site, status: :created, location: @site }
      else
        format.html { render action: "new" }
        format.json { render json: @site.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    @site = Site.find(params[:id])

    respond_to do |format|
      if @site.update_attributes(params[:site])
        format.html { redirect_to @site, notice: 'Site was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @site.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @site = Site.find(params[:id])
    @site.destroy

    respond_to do |format|
      format.html { redirect_to sites_url }
      format.json { head :no_content }
    end
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/sites_helper.rb
module SitesHelper
end

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title><%= content_for?(:title) ? yield(:title) : "Tv" %></title>
<%= csrf_meta_tags %>

<!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
<!--[if lt IE 9]>
  <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
<![endif]-->

<%= stylesheet_link_tag "application", :media => "all" %>
</head>
<body>

<div class="navbar navbar-fluid-top">
  <div class="navbar-inner">
    <div class="container-fluid">
      <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>
      <%= link_to 'Tv', root_path, class: 'brand' %>
      <div class="container-fluid nav-collapse">
        <ul class="nav">
          <li><%= link_to "Sites", sites_path  %></li>
        </ul>
      </div><!--/.nav-collapse -->
    </div>
  </div>
</div>

<div class="container-fluid">
  <div class="row-fluid">

    <div class="span12">
      <%= bootstrap_flash %>
      <%= yield %>
    </div>
  </div><!--/row-->

  <footer>
    <p>&copy; 2012</p>
  </footer>

</div> <!-- /container -->

<%= javascript_include_tag "application" %>

</body>
</html>

app/views/sites/_form.html.erb
<%= form_for @site, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :url, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :url, :class => 'text_field' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                sites_path, :class => 'btn' %>
  </div>
<% end %>

app/views/sites/edit.html.erb
<%- model_class = Site -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human,
                                   :default => "Edit #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/sites/index.html.erb
<%- model_class = Site -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:url) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @sites.each do |site| %>
      <tr>
        <td><%= link_to site.id, site_path(site) %></td>
        <td><%= site.url %></td>
        <td><%=l site.created_at %></td>
        <td>
          <%= link_to 'Show', site_path(site), class: 'btn btn-mini' %>
          <%= link_to 'Edit', edit_site_path(site), class: 'btn btn-mini' %>
          <%= link_to 'Delete', site_path(site), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'New', new_site_path, class: 'btn btn-primary' %>

app/views/sites/new.html.erb
<%- model_class = Site -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human,
                                 :default => "New #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/sites/show.html.erb
<%- model_class = Site -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:url) %>:</strong></dt>
  <dd><%= @site.url %></dd>
</dl>


<% @site.page.each do |url| %>
<p>concur: <%= url %></p>
<iframe src="<%= url %>" width="800" height="600"></iframe>
<% end %>



<div class="form-actions">
  <%= link_to 'Back', sites_path, :class => 'btn'  %>
  <%= link_to 'Edit', edit_site_path(@site), :class => 'btn' %>
  <%= link_to 'Destroy', site_path(@site), :method => 'delete', :data => { :confirm => 'Are you sure?' }, :class => 'btn btn-danger' %>
</div>